### ISSUE TITLE
git config per dir

### ISSUE THREAD

**Issue by jthegedus** [jthegedus/dotfiles#68]
**Is your feature request related to a problem? Please describe.**

I often have multiple folders at work for different clients (`projects-company1`, `projects-company2` etc) and want to automatically change git config user per directory.

**Describe the solution you'd like**

Use the solutions described here - https://stackoverflow.com/a/43884702/7911479

**Describe alternatives you've considered**

manually changing

**Additional context**

```toml
# ~/.gitconfig
[includeIf "gitdir:~/projects/"]
	path = ~/projects/.gitconfig
[includeIf "gitdir:~/projects-COMPANY_NAME/"]
	path = ~/projects-COMPANY_NAME/.gitconfig
[core]
	editor = code --wait
[credential]
	helper = cache --timeout 7200
[pull]
	ff = only

# ~/projects/.gitconfig
[user]
	name = jthegedus
	email = jthegedus@hey.com

# ~/projects-COMPANY_NAME/.gitconfig
[user]
	name = James Hegedus
	email = james.hegedus@COMPANY_NAME.com
```
